dist: Xenial
language: node_js
node_js:
- lts/*
cache: npm
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: mohammedessehemy@gmail.com
  api_key:
    secure: BHeu3qRLgu0chGQTGpTlHXurUDyD0jLfHF4ooowCJ2gxLAmWN22PKj64aYMghXXUKGQJjUc86lMER8MIrUGEHoomQdnBdBaZRwr+9rGfiwjwXbRntpwkcwTfv1R3TXIbEPP20fbiHr+tstD+CflxObqHDD9CJfLDk8Psea47KxNP9uqfkNOxaQhuhdajBdND/FlgrTdnyhIEK+6pkg0VRtN7hNP9VBs9hCW7tDQAL6H8wHgc6NQj2xyOfeyXNZmvpPa/sD6LfcGJK/weI74fKLP7Kb1ub82hOwQrm+ZV7g9fyE88txQw1iHUq3frnBdpW0IiFKKtfuwxH/jlYWbBGYM2zEoOxsC1aRvw2JQb6ExkJvm7px4M5gnfmtgNZDtQX4oS5a2uUtM2mxoxi+PvlrI5I3q9KfSGdT6MR5U7fR3A2HCw75/sb6CPMLh2n1/DpB5AUUbGJyvVAp50EGMnF9j3D31oOigXJovJPVtZHZEss1lEEc/W9OqA5H21nyRr2AC3ruLu2Lvu3xqrIvZHVHbwWHf1WD6GVa3/pBrHousyYifSzrj7M4VwbkIOPw3Xow7yKlFS/QRtNQTD5JjZ4LgkvNDfrPRsNutAD5K+m5LXabF5ZFfekyIUiZOTm7RsvTLUncZpX8qaZhtCpCovt5vycZYO+oFk/ONfSaBGeJk=
  on:
    branch: master
